# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dobi/Dropbox/INFORMATKA/sem4/POBR/projekt/projekt_clion

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dobi/Dropbox/INFORMATKA/sem4/POBR/projekt/projekt_clion

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dobi/Dropbox/INFORMATKA/sem4/POBR/projekt/projekt_clion/CMakeFiles /home/dobi/Dropbox/INFORMATKA/sem4/POBR/projekt/projekt_clion/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dobi/Dropbox/INFORMATKA/sem4/POBR/projekt/projekt_clion/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named open_cv

# Build rule for target.
open_cv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open_cv
.PHONY : open_cv

# fast build rule for target.
open_cv/fast:
	$(MAKE) -f CMakeFiles/open_cv.dir/build.make CMakeFiles/open_cv.dir/build
.PHONY : open_cv/fast

ImageMoments.o: ImageMoments.cpp.o

.PHONY : ImageMoments.o

# target to build an object file
ImageMoments.cpp.o:
	$(MAKE) -f CMakeFiles/open_cv.dir/build.make CMakeFiles/open_cv.dir/ImageMoments.cpp.o
.PHONY : ImageMoments.cpp.o

ImageMoments.i: ImageMoments.cpp.i

.PHONY : ImageMoments.i

# target to preprocess a source file
ImageMoments.cpp.i:
	$(MAKE) -f CMakeFiles/open_cv.dir/build.make CMakeFiles/open_cv.dir/ImageMoments.cpp.i
.PHONY : ImageMoments.cpp.i

ImageMoments.s: ImageMoments.cpp.s

.PHONY : ImageMoments.s

# target to generate assembly for a file
ImageMoments.cpp.s:
	$(MAKE) -f CMakeFiles/open_cv.dir/build.make CMakeFiles/open_cv.dir/ImageMoments.cpp.s
.PHONY : ImageMoments.cpp.s

ImageProcessing.o: ImageProcessing.cpp.o

.PHONY : ImageProcessing.o

# target to build an object file
ImageProcessing.cpp.o:
	$(MAKE) -f CMakeFiles/open_cv.dir/build.make CMakeFiles/open_cv.dir/ImageProcessing.cpp.o
.PHONY : ImageProcessing.cpp.o

ImageProcessing.i: ImageProcessing.cpp.i

.PHONY : ImageProcessing.i

# target to preprocess a source file
ImageProcessing.cpp.i:
	$(MAKE) -f CMakeFiles/open_cv.dir/build.make CMakeFiles/open_cv.dir/ImageProcessing.cpp.i
.PHONY : ImageProcessing.cpp.i

ImageProcessing.s: ImageProcessing.cpp.s

.PHONY : ImageProcessing.s

# target to generate assembly for a file
ImageProcessing.cpp.s:
	$(MAKE) -f CMakeFiles/open_cv.dir/build.make CMakeFiles/open_cv.dir/ImageProcessing.cpp.s
.PHONY : ImageProcessing.cpp.s

Processing.o: Processing.cpp.o

.PHONY : Processing.o

# target to build an object file
Processing.cpp.o:
	$(MAKE) -f CMakeFiles/open_cv.dir/build.make CMakeFiles/open_cv.dir/Processing.cpp.o
.PHONY : Processing.cpp.o

Processing.i: Processing.cpp.i

.PHONY : Processing.i

# target to preprocess a source file
Processing.cpp.i:
	$(MAKE) -f CMakeFiles/open_cv.dir/build.make CMakeFiles/open_cv.dir/Processing.cpp.i
.PHONY : Processing.cpp.i

Processing.s: Processing.cpp.s

.PHONY : Processing.s

# target to generate assembly for a file
Processing.cpp.s:
	$(MAKE) -f CMakeFiles/open_cv.dir/build.make CMakeFiles/open_cv.dir/Processing.cpp.s
.PHONY : Processing.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/open_cv.dir/build.make CMakeFiles/open_cv.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/open_cv.dir/build.make CMakeFiles/open_cv.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/open_cv.dir/build.make CMakeFiles/open_cv.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... open_cv"
	@echo "... ImageMoments.o"
	@echo "... ImageMoments.i"
	@echo "... ImageMoments.s"
	@echo "... ImageProcessing.o"
	@echo "... ImageProcessing.i"
	@echo "... ImageProcessing.s"
	@echo "... Processing.o"
	@echo "... Processing.i"
	@echo "... Processing.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

